# Generated by Django 5.0.6 on 2024-10-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app_root_security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationMediaFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='authentication_medias')),
            ],
        ),
    ]
