# Generated by Django 5.0.6 on 2024-10-18 05:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app_root_home_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeManamentView',
            new_name='HomeManagementView',
        ),
    ]
