# Generated by Django 5.0.6 on 2024-07-11 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app_root_chat_management', '0005_questionandanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionandanswer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='storeuserchatmodel',
            name='user',
        ),
    ]
