# Generated by Django 5.0.6 on 2024-07-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app_root_chat_management', '0008_userhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionandanswer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
