# Generated by Django 5.0.6 on 2024-07-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app_root_chat_management', '0010_alter_userhistory_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenieQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('genie_question', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenieResponseToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('genie_response', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user_questions', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserResponseToGenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user_response', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
