# Generated by Django 5.0.6 on 2024-10-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_subscription', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
