# Generated by Django 4.2.13 on 2024-06-03 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HumanQualities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_color', models.CharField(blank=True, max_length=500, null=True)),
                ('shirt_size', models.CharField(max_length=200)),
                ('hobbies', models.CharField(max_length=100)),
                ('is_hot_tempered', models.BooleanField(default=False)),
            ],
        ),
    ]
