# Generated by Django 5.0.6 on 2024-06-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HumanQualities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skin_color",
                    models.CharField(
                        blank=True,
                        choices=[("G", "Gray"), ("W", "White"), ("B", "Black")],
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "shirt_size",
                    models.CharField(
                        choices=[("S", "Small"), ("M", "Medium"), ("H", "Huge")],
                        max_length=1,
                    ),
                ),
                (
                    "hobbies",
                    models.CharField(
                        choices=[
                            ("SING", "Singing"),
                            ("DANCE", "DANCING"),
                            ("COOK", "COOKING"),
                        ],
                        max_length=100,
                    ),
                ),
                ("is_hot_tempered", models.BooleanField(default=False)),
            ],
        ),
    ]
