# Generated by Django 4.2.13 on 2024-06-03 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app_root_human_attributes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='humanqualities',
            old_name='shirt_size',
            new_name='body_size',
        ),
    ]
