# Generated by Django 5.0.6 on 2024-06-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "core_app_root_human_attributes",
            "0005_remove_humanqualities_gender_humaninterests_user_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="humaninterests",
            options={"verbose_name_plural": "HumanInterests"},
        ),
        migrations.AddField(
            model_name="humaninterests",
            name="gym_and_fitness",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="humaninterests",
            name="language",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="humaninterests",
            name="people",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="humaninterests",
            name="photography",
            field=models.BooleanField(default=False),
        ),
    ]
