# Generated by Django 5.0.6 on 2024-10-17 21:07

import django.db.models.deletion
import multiselectfield.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingPrivacyModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opening_move', models.CharField(max_length=500, null=True)),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Setting Privacy Model',
                'verbose_name_plural': 'Setting Privacy Models',
            },
        ),
        migrations.CreateModel(
            name='QualitiesValueModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quality', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app_root_security_settings_and_privacy.settingprivacymodel')),
            ],
            options={
                'verbose_name': 'QualitiesValueModel',
                'verbose_name_plural': 'QualitiesValueModels',
            },
        ),
        migrations.CreateModel(
            name='MatchPreferenceModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drinking', models.CharField(choices=[('Y', 'Yes'), ('S', 'Sometimes'), ('N', 'No')], max_length=1, null=True)),
                ('smoking', models.CharField(choices=[('Y', 'Yes'), ('S', 'Sometimes'), ('N', 'No')], max_length=1, null=True)),
                ('education_level', multiselectfield.db.fields.MultiSelectField(choices=[('Technical Eduation', 'Technical Education'), ('Diploma Education', 'Diploma Education'), ("Associate's Degree", "Associate's Degree"), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Doctorate Degree (Ph.D)', 'Doctorate Degree (Ph.D)')], max_length=113, null=True)),
                ('min_age', models.PositiveIntegerField()),
                ('max_age', models.PositiveIntegerField()),
                ('min_height', models.PositiveIntegerField()),
                ('max_height', models.PositiveIntegerField()),
                ('distance', models.PositiveIntegerField()),
                ('relationship_goals', models.CharField(choices=[('A long-term relationship', 'A long-term relationship'), ('A life partner', 'A life partner'), ('Fun casual dates', 'Fun casual dates'), ('Intimacy, without commitment', 'Intimacy , without commitment'), ('Marriage', 'Marriage'), ('Ethical Non-monogamy', 'Ethical Non-monogamy')], max_length=255, null=True)),
                ('occupation', multiselectfield.db.fields.MultiSelectField(choices=[('Accountant', 'Accountant'), ('Chef', 'Chef'), ('Civil Engineer', 'Civil Engineer'), ('Customer Service Rep', 'Customer Service Rep'), ('Data Analyst', 'Data Analyst'), ('Electrician', 'Electrician'), ('Financial Analyst', 'Financial Analyst'), ('Graphic Designer', 'Graphic Designer'), ('Human Resource', 'Human Resource'), ('Marketing', 'Marketing'), ('Mechanical Engineer', 'Mechanical Engineer'), ('Operations Manager', 'Operations Manager'), ('Pharmacist', 'Pharmacist'), ('Physical Therapist', 'Physical Therapist'), ('Registered Nurse', 'Registered Nurse'), ('Sale Representative', 'Sale Representative'), ('Socal Worker', 'Socal Worker'), ('Software Developer', 'Software Developer'), ('Surgeon', 'Surgeon'), ('Teacher', 'Teacher'), ('Web Developer', 'Web Developer'), ('Doctor', 'Doctor')], max_length=311, null=True)),
                ('body_build', multiselectfield.db.fields.MultiSelectField(choices=[('Plus Size', 'Plus Size'), ('Slim', 'Slim'), ('Athletic', 'Athletic'), ('Curvy', 'Curvy'), ('Petite', 'Petite')], max_length=36, null=True)),
                ('religion', multiselectfield.db.fields.MultiSelectField(choices=[('Agnostic', 'Agnostic'), ('Atheist', 'Atheist'), ('Buddhist', 'Buddhist'), ('Catholic', 'Catholic'), ('Christian', 'Christian'), ('Hindu', 'Hindu'), ('Jewish', 'Jewish'), ('Morman', 'Morman'), ('Muslim', 'Muslim'), ('Latter-day Saint', 'Latter-day Saint'), ('Spiritual', 'Spiritual')], max_length=98, null=True)),
                ('politics', multiselectfield.db.fields.MultiSelectField(choices=[('Apolitical', 'Apolitical'), ('Conservative', 'Conservative'), ('Liberal', 'Liberal'), ('Moderate', 'Moderate')], max_length=40, null=True)),
                ('setting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core_app_root_security_settings_and_privacy.settingprivacymodel')),
            ],
            options={
                'verbose_name': 'Match Preference Model',
                'verbose_name_plural': 'Match Preference Models',
            },
        ),
        migrations.CreateModel(
            name='CausesModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('causes', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app_root_security_settings_and_privacy.settingprivacymodel')),
            ],
            options={
                'verbose_name': 'Cause and Community',
                'verbose_name_plural': 'Cause and Communities',
            },
        ),
    ]
