# Generated by Django 5.0.6 on 2024-10-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app_root_security_settings_and_privacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchpreferencemodel',
            name='distance',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchpreferencemodel',
            name='max_age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchpreferencemodel',
            name='max_height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchpreferencemodel',
            name='min_age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matchpreferencemodel',
            name='min_height',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
