# Generated by Django 5.0.6 on 2024-10-17 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app_root_security_settings_and_privacy', '0002_alter_matchpreferencemodel_distance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='causesmodel',
            old_name='user',
            new_name='setting',
        ),
        migrations.RenameField(
            model_name='qualitiesvaluemodel',
            old_name='user',
            new_name='setting',
        ),
    ]
