# Generated by Django 5.0.6 on 2024-10-18 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app_root_security_settings_and_privacy', '0003_rename_user_causesmodel_setting_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qualitiesvaluemodel',
            options={'verbose_name': 'Qualities and Value Model', 'verbose_name_plural': 'Qualities and Value Models'},
        ),
    ]
