# Generated by Django 5.0.6 on 2024-10-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app_root_security_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleLoginModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
        ),
    ]
