# Generated by Django 4.2.13 on 2024-06-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app_root_match_friends", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userattributes",
            name="age",
            field=models.IntegerField(),
        ),
    ]
