# Generated by Django 4.2.13 on 2024-06-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app_root_match_friends", "0002_alter_userattributes_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userattributes",
            name="age",
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name="userattributes",
            name="country",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
