# Generated by Django 5.0.6 on 2024-07-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app_root_match_friends', '0004_askquestionstomatchmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchFriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
