# Generated by Django 5.0.6 on 2024-07-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app_root_match_friends', '0005_matchfriend'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchfriend',
            name='user_email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchfriend',
            name='user_email_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchfriend',
            name='user_partner_email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchfriend',
            name='user_partner_email_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
