# Generated by Django 5.0.6 on 2024-08-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app_root_match_friends', '0006_matchfriend_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchedFriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.TextField(blank=True, null=True)),
                ('user_partner_email', models.TextField(blank=True, null=True)),
                ('time_matched', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
