# Generated by Django 5.0.6 on 2024-10-01 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app_root_match_friends', '0007_matchedfriend'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchedfriend',
            name='accept_match',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchedfriend',
            name='reject_match',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
