# Generated by Django 5.0.6 on 2024-10-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app_root_match_friends', '0008_matchedfriend_accept_match_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchedfriend',
            name='accept_match',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='matchedfriend',
            name='reject_match',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
