# Generated by Django 5.0.6 on 2024-10-01 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app_root_match_friends', '0009_alter_matchedfriend_accept_match_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchedfriend',
            old_name='accept_match',
            new_name='swipe_left',
        ),
        migrations.RenameField(
            model_name='matchedfriend',
            old_name='reject_match',
            new_name='swipe_right',
        ),
    ]
