# Generated by Django 5.0.6 on 2024-10-15 10:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app_root_match_friends', '0010_rename_accept_match_matchedfriend_swipe_left_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterMatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interested_in', models.CharField(blank=True, max_length=200, null=True)),
                ('language', models.CharField(blank=True, max_length=300, null=True)),
                ('age_range', models.CharField(blank=True, max_length=300, null=True)),
                ('amount_of_apples', models.CharField(blank=True, max_length=300, null=True)),
                ('travel_mode', models.CharField(blank=True, default=False, null=True)),
                ('distance_range', models.CharField(blank=True, default=False, null=True)),
                ('interests', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100000), size=None)),
            ],
        ),
    ]
