# Generated by Django 4.2.13 on 2024-06-03 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppleGiftingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_apples', models.IntegerField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
            ],
        ),
    ]
