# Generated by Django 5.0.6 on 2024-06-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app_root_apple_gifting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="applegiftingmodel",
            name="is_expired",
            field=models.BooleanField(default=False),
        ),
    ]
