# Generated by Django 5.0.6 on 2024-10-09 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app_root_apple_gifting', '0002_remove_applegiftingmodel_is_expired_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applegiftingmodel',
            name='reciever_accepts',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='applegiftingmodel',
            name='reciever_rejects',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='applemodel',
            name='apple_recieved',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='applemodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
