# Generated by Django 5.0.6 on 2024-10-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app_root_apple_gifting', '0004_alter_applegiftingmodel_reciever_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applegiftingmodel',
            name='sender',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
