# Generated by Django 5.0.6 on 2024-10-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app_root_apple_gifting', '0005_alter_applegiftingmodel_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applegiftingmodel',
            name='reciever_accepts',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
