# Generated by Django 5.0.6 on 2024-10-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app_root_apple_gifting', '0006_alter_applegiftingmodel_reciever_accepts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applemodel',
            name='bucket_of_apple',
            field=models.FloatField(default=10, null=True),
        ),
    ]
