# Generated by Django 5.0.6 on 2024-10-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app_root_apple_gifting', '0007_alter_applemodel_bucket_of_apple'),
    ]

    operations = [
        migrations.AddField(
            model_name='applemodel',
            name='apple_sent',
            field=models.FloatField(default=0, null=True),
        ),
    ]
