# Generated by Django 5.0.6 on 2024-10-11 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app_root_apple_gifting', '0008_applemodel_apple_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applemodel',
            old_name='apple_sent',
            new_name='total_apple_sent',
        ),
    ]
