# Generated by Django 5.0.6 on 2024-10-15 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app_root_apple_gifting', '0009_rename_apple_sent_applemodel_total_apple_sent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppleGiftingModel',
        ),
        migrations.DeleteModel(
            name='AppleModel',
        ),
    ]
