# Generated by Django 5.0.6 on 2024-10-06 16:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app_root_security_user', '0003_user_face_encoding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_title', models.CharField(max_length=2000)),
                ('image', models.FileField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingUserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100000), size=None)),
                ('gender', models.CharField(blank=True, max_length=200)),
                ('primary_interest', models.TextField()),
                ('height', models.CharField(blank=True, max_length=10000)),
                ('opening_move', models.TextField()),
                ('dob', models.DateField(blank=True)),
                ('values', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100000), size=None)),
                ('habits', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100000), size=None)),
                ('family_planning', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100000), size=None)),
                ('beliefs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100000), size=None)),
                ('communities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100000), size=None)),
                ('images', models.ManyToManyField(blank=True, related_name='models', to='core_app_root_security_user.image')),
            ],
        ),
    ]
