# Generated by Django 5.0.6 on 2024-10-06 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app_root_security_user', '0004_image_onboardinguserdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardinguserdetails',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
