# Generated by Django 5.0.6 on 2024-10-09 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app_root_security_user', '0007_alter_onboardinguserdetails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardinguserdetails',
            name='images',
        ),
    ]
