# Generated by Django 5.0.6 on 2024-10-10 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app_root_security_user', '0009_onboardinguserdetails_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardinguserdetails',
            name='otp',
        ),
    ]
