# Generated by Django 5.0.6 on 2024-10-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app_root_security_user', '0010_remove_onboardinguserdetails_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardinguserdetails',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
