# Generated by Django 5.0.6 on 2024-10-11 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app_root_security_user', '0011_onboardinguserdetails_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardinguserdetails',
            name='phone',
            field=models.CharField(blank=True, null=True),
        ),
    ]
