# Generated by Django 5.0.6 on 2024-10-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app_root_security_user', '0012_alter_onboardinguserdetails_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='onboardinguserdetails',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardinguserdetails',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardinguserdetails',
            name='home_town',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardinguserdetails',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='kyc_images'),
        ),
    ]
