# Generated by Django 5.0.6 on 2024-10-11 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app_root_security_user', '0013_delete_image_onboardinguserdetails_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardinguserdetails',
            name='profile_photo',
        ),
    ]
