# Generated by Django 5.0.6 on 2024-10-11 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app_root_security_user', '0016_alter_onboardinguserdetails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardinguserdetails',
            name='phone',
        ),
        migrations.CreateModel(
            name='PhoneNumbersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_phone_numbers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
