# Generated by Django 5.0.6 on 2024-10-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app_root_security_user', '0017_remove_onboardinguserdetails_phone_phonenumbersmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardinguserdetails',
            name='otp',
        ),
        migrations.AddField(
            model_name='phonenumbersmodel',
            name='code',
            field=models.CharField(blank=True, null=True),
        ),
    ]
