# Generated by Django 5.0.6 on 2024-10-15 23:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app_root_security_user', '0020_applegiftingmodel_applemodel_userprofilesummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardinguserdetails',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='user_images'),
        ),
        migrations.AddField(
            model_name='onboardinguserdetails',
            name='preferred_quality_in_others',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10000, null=True), blank=True, null=True, size=None),
        ),
    ]
