# Generated by Django 5.0.6 on 2024-10-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app_root_security_user', '0022_user_customer_user_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilesummary',
            name='apple_details',
        ),
        migrations.RemoveField(
            model_name='userprofilesummary',
            name='phone_number_detail',
        ),
        migrations.RemoveField(
            model_name='userprofilesummary',
            name='user_auth_details',
        ),
        migrations.RemoveField(
            model_name='userprofilesummary',
            name='user_onboarding_details',
        ),
        migrations.AddField(
            model_name='userprofilesummary',
            name='age_range',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofilesummary',
            name='amount_of_apple_range',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofilesummary',
            name='distance_range',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofilesummary',
            name='interested_in',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofilesummary',
            name='interests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofilesummary',
            name='language',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofilesummary',
            name='travel_mode_on',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
