# Generated by Django 5.0.6 on 2024-10-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app_root_security_user', '0023_remove_userprofilesummary_apple_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardinguserdetails',
            name='age',
            field=models.CharField(blank=True, null=True),
        ),
    ]
